export enum Permission {
  CREATE_INVITE = 'CREATE_INVITE',
  DELETE_INVITE = 'DELETE_INVITE',
  VIEW_INVITE = 'VIEW_INVITE',
  UPDATE_INVITE = 'UPDATE_INVITE',

  VIEW_STAFF = 'VIEW_STAFF',
  DELETE_STAFF = 'DELETE_STAFF',

  VIEW_PROCUREMENT = 'VIEW_PROCUREMENT',
  CREATE_PROCUREMENT = 'CREATE_PROCUREMENT',
  DELETE_PROCUREMENT = 'DELETE_PROCUREMENT',
  UPDATE_PROCUREMENT = 'UPDATE_PROCUREMENT',

  VIEW_PRODUCT = 'VIEW_PRODUCT',
  CREATE_PRODUCT = 'CREATE_PRODUCT',
  UPDATE_PRODUCT = 'CREATE_PRODUCT',
  DELETE_PRODUCT = 'DELETE_PRODUCT',

  UPDATE_ORGANIZATION_PROFILE = 'UPDATE-ORGANIZATION-PROFILE',

  CREATE_PROPOSAL = 'CREATE_PROPOSAL',
  VIEW_PROPOSAL = 'VIEW_PROPOSAL',
  UPDATE_PROPOSAL = 'UPDATE_PROPOSAL',
  DELETE_PROPOSAL = 'DELETE_PROPOSAL',

  CREATE_PROPOSAL_REQUEST = 'CREATE_PROPOSAL_REQUEST',
  VIEW_PROPOSAL_REQUEST = 'VIEW_PROPOSAL_REQUEST',
  UPDATE_PROPOSAL_REQUEST = 'UPDATE_PROPOSAL_REQUEST',
  DELETE_PROPOSAL_REQUEST = 'DELETE_PROPOSAL_REQUEST',

  CREATE_TASK = 'CREATE_TASK',
  VIEW_TASK = 'VIEW_TASK',
  UPDATE_TASK = 'UPDATE_TASK',
  DELETE_TASK = 'DELETE_TASK',

  DELETE_ACCOUNT = 'DELETE_ACCOUNT',

  VIEW_ORDER = 'VIEW_ORDER',
  UPDATE_ORDER = 'UPDATE_ORDER',
}
